### PR TITLE
Add stats to embed

### PR DESCRIPTION
**Pull request by robbiet480**
Add views, likes, reposts and comments count stats to embed (inspiration from FixTwitter) in addition to slight improvement to the author line and add the description.

### CODE REVIEW

**Comment by dylanpdx** [comment]
Just making sure, have you tested this locally to make sure all the right info is being retrieved?

**Comment by robbiet480** [comment]
Yep, although full disclosure I couldn't test the final output with the description added due to Discord soft blocking my URL embed access (I guess?)

Here's the last thing I saw:
image

**Comment by dylanpdx** [comment]
Cool! That works for me 👍 Thanks for the PR :)

**Comment by robbiet480** [comment]
@dylanpdx are you seeing _any_ urls with embeds in Discord right now? Looks like their service for grabbing oembeds might have just gone down?

**Comment by robbiet480** [comment]
lol yep they broke it coincidentally at the same time https://discordstatus.com/incidents/5xycpkzntbr2

**Comment by robbiet480** [comment]
Final product looks good!
image

**Comment by dylanpdx** [comment]
Yup, seems to be working now!

**Comment by robbiet480** [comment]
Turns out the description won't come through on video players. I think it's more valuable to have the stats, usually the description is just hashtags or empty. But let me know if you'd rather have the description and I can add it into the text area currently used by the stats.

**Comment by dylanpdx** [comment]
Yeah I agree the stats are better to have rather than the description, so leaving it as is sounds good to me

**Pull request merged**
