### PR TITLE
Add shortlink support, remove the need for config domain name

### PR DESCRIPTION
**Pull request by iGerman00**
Nice service, but I found it to be pretty useless for links that come from the mobile app, because they are shortened links. 

So, I've added support for links that look like:
`vt.tiktok.com/Z9ULvrKAn` (fake link)

The mechanism behind it is just fetching the short link. It returns a 301 with a Location header which contains a long link - just what we need for yt-dlp
I've also changed how it detects the username links; that includes not having to worry about the config domain name anymore.

To use this, all you have to do is paste the link after the domain, like so:
`https://vxtiktok.com/vt.tiktok.com/Z9ULvrKAn`.
Not the best solution but I didn't have other ideas. 

I've tested it on my selfhosted instance, seemed to work fine.

<sub>P.S. your instance seems to be broken right now, hope you can fix it soon. It always returns `{"message":"Internal Server Error"}`</sub>

### CODE REVIEW

**Comment by dylanpdx** [comment]
Hey!

Shortlinks actually worked beforehand as I have a subdomain configuration for the site, so *.vxtiktok.com auto gets redirected to vxtiktok.com
It used to work, but I think something changed that causes yt-dlp to be unable to properly parse these

**Comment by iGerman00** [comment]
> Hey!
> 
> Shortlinks actually worked beforehand as I have a subdomain configuration for the site, so *.vxtiktok.com auto gets redirected to vxtiktok.com It used to work, but I think something changed that causes yt-dlp to be unable to properly parse these and time out the request
> 
> With your example, it should be as simple as changing it from `vt.tiktok.com/Z9ULvrKAn` to `vt.vxtiktok.com/Z9ULvrKAn`

Huh, I didn't know that! It does indeed work right now. Perhaps when I tested, it was in a nonworking state, so I concluded it never worked. Right now it does indeed work with shortlinks, but not long links, weird.

**Comment by dylanpdx** [comment]
From my testing, it looks to me like yt-dlp is the issue, as it hangs for a long time on
```
[vm.tiktok] <shortlink>: Downloading webpage
[generic] www.tiktok: Downloading webpage 
```

Not sure if that means I'll have to implement my own way to access the API instead of using yt-dlp

**Comment by iGerman00** [comment]
> From my testing, it looks to me like yt-dlp is the issue, as it hangs for a long time on
> 
> ```
> [vm.tiktok] <shortlink>: Downloading webpage
> [generic] www.tiktok: Downloading webpage 
> ```
> 
> Not sure if that means I'll have to implement my own way to access the API instead of using yt-dlp

Not sure either. I'm running what I'm PRing @ https://tiktok.igerman.cc and it's working fine on long links (since it converts shortlinks to longlinks right away), never knew yt-dlp could parse shortlinks anyway haha

**Pull request merged**
